package rzrz.java.lang;

import java.util.NoSuchElementException;

/**
 *  AUTOGENERATED FILE: DO NOT MODIFY
 *  @see src/main/templates/rzrz/java/lang/GenerateSources.js
 *  @author Jacek Rzeniewicz
 */
public final class Exceptions {


	public static class ArrayIndexOutOfBounds extends ArrayIndexOutOfBoundsException {

		public ArrayIndexOutOfBounds() {
			super();
		}

		public ArrayIndexOutOfBounds(String message) {
			super(message);
		}

		public ArrayIndexOutOfBounds(String messageFormat, Object... messageArgs) {
			this(String.format(messageFormat, messageArgs));
		}

	}


	public static class ArrayStore extends ArrayStoreException {

		public ArrayStore() {
			super();
		}

		public ArrayStore(String message) {
			super(message);
		}

		public ArrayStore(String messageFormat, Object... messageArgs) {
			this(String.format(messageFormat, messageArgs));
		}

	}


	public static class IllegalAccess extends IllegalAccessException {

		public IllegalAccess() {
			super();
		}

		public IllegalAccess(String message) {
			super(message);
		}

		public IllegalAccess(String messageFormat, Object... messageArgs) {
			this(String.format(messageFormat, messageArgs));
		}

	}


	public static class IllegalArgument extends IllegalArgumentException {

		public IllegalArgument() {
			super();
		}

		public IllegalArgument(String message) {
			super(message);
		}

		public IllegalArgument(String messageFormat, Object... messageArgs) {
			this(String.format(messageFormat, messageArgs));
		}


		public IllegalArgument(Throwable cause) {
			super(cause);
		}

		public IllegalArgument(Throwable cause, String message) {
			super(message, cause);
		}

		public IllegalArgument(Throwable cause, String messageFormat, Object... messageArgs) {
			this(cause, String.format(messageFormat, messageArgs));
		}

	}


	public static class IllegalState extends IllegalStateException {

		public IllegalState() {
			super();
		}

		public IllegalState(String message) {
			super(message);
		}

		public IllegalState(String messageFormat, Object... messageArgs) {
			this(String.format(messageFormat, messageArgs));
		}


		public IllegalState(Throwable cause) {
			super(cause);
		}

		public IllegalState(Throwable cause, String message) {
			super(message, cause);
		}

		public IllegalState(Throwable cause, String messageFormat, Object... messageArgs) {
			this(cause, String.format(messageFormat, messageArgs));
		}

	}


	public static class IndexOutOfBounds extends IndexOutOfBoundsException {

		public IndexOutOfBounds() {
			super();
		}

		public IndexOutOfBounds(String message) {
			super(message);
		}

		public IndexOutOfBounds(String messageFormat, Object... messageArgs) {
			this(String.format(messageFormat, messageArgs));
		}

	}


	public static class NegativeArraySize extends NegativeArraySizeException {

		public NegativeArraySize() {
			super();
		}

		public NegativeArraySize(String message) {
			super(message);
		}

		public NegativeArraySize(String messageFormat, Object... messageArgs) {
			this(String.format(messageFormat, messageArgs));
		}

	}


	public static class NoSuchElement extends NoSuchElementException {

		public NoSuchElement() {
			super();
		}

		public NoSuchElement(String message) {
			super(message);
		}

		public NoSuchElement(String messageFormat, Object... messageArgs) {
			this(String.format(messageFormat, messageArgs));
		}

	}


	public static class NullPointer extends NullPointerException {

		public NullPointer() {
			super();
		}

		public NullPointer(String message) {
			super(message);
		}

		public NullPointer(String messageFormat, Object... messageArgs) {
			this(String.format(messageFormat, messageArgs));
		}

	}


	public static class NumberFormat extends NumberFormatException {

		public NumberFormat() {
			super();
		}

		public NumberFormat(String message) {
			super(message);
		}

		public NumberFormat(String messageFormat, Object... messageArgs) {
			this(String.format(messageFormat, messageArgs));
		}

	}


	public static class StringIndexOutOfBounds extends StringIndexOutOfBoundsException {

		public StringIndexOutOfBounds() {
			super();
		}

		public StringIndexOutOfBounds(String message) {
			super(message);
		}

		public StringIndexOutOfBounds(String messageFormat, Object... messageArgs) {
			this(String.format(messageFormat, messageArgs));
		}

	}


	public static class UnsupportedOperation extends UnsupportedOperationException {

		public UnsupportedOperation() {
			super();
		}

		public UnsupportedOperation(String message) {
			super(message);
		}

		public UnsupportedOperation(String messageFormat, Object... messageArgs) {
			this(String.format(messageFormat, messageArgs));
		}


		public UnsupportedOperation(Throwable cause) {
			super(cause);
		}

		public UnsupportedOperation(Throwable cause, String message) {
			super(message, cause);
		}

		public UnsupportedOperation(Throwable cause, String messageFormat, Object... messageArgs) {
			this(cause, String.format(messageFormat, messageArgs));
		}

	}

}