{{! Template of Exceptions.java }}
package rzrz.java.lang;

{{#each exceptions}}
{{#if package}}
import {{package}}.{{name}}Exception;
{{/if}}
{{/each}}

/**
 *  AUTOGENERATED FILE: DO NOT MODIFY
 *  @see src-gen/generate.js
 *  @author Jacek Rzeniewicz
 */
public final class Exceptions {

	{{#each exceptions}}

	public static class {{name}} extends {{name}}Exception {

		public {{name}}() {
			super();
		}

		public {{name}}(String message) {
			super(message);
		}

		public {{name}}(String messageFormat, Object... messageArgs) {
			this(String.format(messageFormat, messageArgs));
		}

		{{#if cause}}

		public {{name}}(Throwable cause) {
			super(cause);
		}

		public {{name}}(Throwable cause, String message) {
			super(message, cause);
		}

		public {{name}}(Throwable cause, String messageFormat, Object... messageArgs) {
			this(cause, String.format(messageFormat, messageArgs));
		}

		{{/if}}
	}

	{{/each}}
}