{{! Template of Functions.java }}
package rzrz.java.lang;

import java.lang.RuntimeException;

/**
 *  AUTOGENERATED FILE: DO NOT MODIFY
 *  @see src/main/templates/rzrz/java/lang/GenerateSources.js
 *  @author Jacek Rzeniewicz
 */
public final class Functions {

	{{#each arities}}

	/*
	 * {{this}}-argument functions
	 */

	{{#each ../functions}}

	public interface {{name.short}}{{@..}}ThrowsT<{{typeParams @..}}{{delim @.. '&' ret.param}}{{ret.param}}{{delim @.. '|' ret.param}}TError extends Throwable> {

		{{ret.type}} call({{args @..}}) throws TError;
	}

	public interface {{name.short}}{{@..}}ThrowsE{{lang @.. ret.param}}{{typeParams @..}}{{delim @.. '&' ret.param}}{{ret.param}}{{rang @.. ret.param}}
		extends {{name.short}}{{@..}}ThrowsT<{{typeParams @..}}{{delim @.. '&' ret.param}}{{ret.param}}{{delim @.. '|' ret.param}}Exception>
	{

	}

	public interface {{name.short}}{{@..}}{{lang @.. ret.param}}{{typeParams @..}}{{delim @.. '&' ret.param}}{{ret.param}}{{rang @.. ret.param}}
		extends {{name.short}}{{@..}}ThrowsT<{{typeParams @..}}{{delim @.. '&' ret.param}}{{ret.param}}{{delim @.. '|' ret.param}}RuntimeException>
	{

	}
	{{/each}}
	{{/each}}
}